config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

	root 'dashboards#index'
	resources :users do
    collection do
      post :upload_file
    end
  end

	namespace :admin do
    resources :assignments do
    	member do
	      post :sent_to_users
    	end
    end
    resources :dashboards, only: [:index]
    resources :users, only: [:index, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :admin]  


  has_many :assignment_users, dependent: :destroy
  has_many :assignments, through: :assignment_users   
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
	before_action :set_user, only: [:destroy]
	def index
		@users = User.user
	end

	def destroy
		if @user.destroy
      flash[:notice] = 'user successfully deleted'
    else
      flash[:alert]  = 'Error in deleting the user'
    end
    redirect_to admin_users_path
	end

	private

    def set_user
      @user = User.find params[:id]
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
    end

    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :role])
    end

    def after_sign_up_path_for(_resource)
      if current_user.admin?
        admin_dashboards_path
      else
        root_path
      end
    end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

    def after_sign_in_path_for(_resource)
      if current_user.admin?
        admin_dashboards_path
      else
        root_path
      end
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @assignments = Assignment.all.where(sent_to_users: true)
  end

  def upload_file
    user_assignment = current_user.assignment_users.find_by(assignment_id: params[:assignment_user][:assignment_id])    
    if user_assignment.present?
      user_assignment.destroy
    end 
    @assignment_user = current_user.assignment_users.new(assignment_params)
    if @assignment_user.save
      save_file_separate_folder
      flash[:notice] = 'File created successfully'
    else
      flash[:alert] = 'File not created successfully'
    end   
    redirect_to users_path  
  end

  def save_file_separate_folder
    assignment = Assignment.find_by(id: params[:assignment_user][:assignment_id])
    uploaded_io = params[:assignment_user][:file]
    File.open(Rails.root.join('public', "#{assignment.title}", "#{current_user.name}_#{uploaded_io.original_filename}"), 'wb') do |file|
      file.write(uploaded_io.read)
    end
  end

  private
    def assignment_params 
      params.require(:assignment_user).permit(:assignment_id, :file)
    end 
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def user_assignment(assignment)
		assignment.assignment_users.find_by(user_id: current_user.id)&.file
	end
end

app/views/users/index.html.erb
<div class="container">
  <%= render 'shared/header' %>
  </br>
  </br>
  <div class="row">
    <div class="col-lg-12">
      <h2 class= 'float-left'><%= current_user.name.humanize %> Assignments!</h2>
    </div>
  </div>
  </br>
  <div class="row">
    <% if @assignments.present? %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th class='text-center'>Title</th>
            <th class='text-center'>Description</th>
            <th class='text-center'>Due Date</th>
            <th class='text-center'>Uploaded File</th>
            <th class='text-center'>Upload Assignment</th>    
          </tr>
        </thead>
        <% @assignments.each do |assignment| %>
          <tbody>
            <tr>
              <td class='text-center'><%= assignment.title %></td>
              <td class='text-center'><%= assignment.description.truncate(20) %></td>
              <td class='text-center'><%= assignment.due_date.strftime('%a %d %b %Y by %l:%M %p') %></td>
              <td class='text-center'>
                <% if user_assignment(assignment)&.attached? %>
                  <%= link_to user_assignment(assignment)&.blob.filename, rails_blob_path(assignment.assignment_users.first.file, disposition: "attachment") %>
                <% else %>
                  Not Uploaded yet
                <% end %>
              </td>
              <td class='text-center'>
                <%= form_for :assignment_user, local: true, url: upload_file_users_path, method: :post, html: { class: 'form-horizontal', 'data-parsley-validate': '' } do |f| %>
                  <div class="input-group">
                    <%= f.hidden_field :assignment_id, value: assignment.id %>
                    <%= f.file_field :file, required: true, class: 'form-control' %>
                    <span class="input-group-btn">
                      <%= f.submit 'Upload', class: 'btn btn-primary btn-group' %>
                    </span>
                  </div>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    <% else %>
      <h4 class='text-center'>You have not been assigned any assignment yet.</h4>
    <% end %>
  </div>
</div>