config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

	root 'dashboards#index'
	resources :users do
    collection do
      post :upload_file
    end
  end

	namespace :admin do
    resources :assignments do
    	member do
	      post :sent_to_users
    	end
    end
    resources :dashboards, only: [:index]
    resources :users, only: [:index, :destroy]
  end
end

app/models/assignment.rb
class Assignment < ApplicationRecord
	has_many :assignment_users, dependent: :destroy
	has_many :users, through: :assignment_users

	validates_uniqueness_of :title
end

app/controllers/admin/assignments_controller.rb
class Admin::AssignmentsController < Admin::BaseController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy, :sent_to_users]

  def index
    @assignments = Assignment.all
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(assignment_params)
    if @assignment.save
      dir = "#{Rails.root}/public/#{@assignment.title}"
      FileUtils.mkdir_p(dir) unless File.directory?(dir)
      redirect_to admin_assignments_path, notice: 'Assignment successfully created'
    else
      render :new
    end
  end

  def update
    if @assignment.update(assignment_params)
      redirect_to admin_assignments_path, notice: 'Assignment successfully updated'
    else
      render :edit
    end
  end

  def show
    @assignment_users = @assignment.assignment_users
  end

  def destroy
    if @assignment.destroy
      flash[:notice] = 'Assignment successfully deleted'
    else
      flash[:alert]  = 'Error in deleting the assignment'
    end
    redirect_to admin_assignments_path
  end

  def sent_to_users
    @assignment.update(sent_to_users: true)
    redirect_to admin_assignments_path, notice: 'Assignment sent to all users'
  end

  private

    def set_assignment
      @assignment = Assignment.find params[:id]
    end

    def assignment_params
      params.require(:assignment).permit(:title, :description, :due_date)
    end
end

app/helpers/admin/assignments_helper.rb
module Admin::AssignmentsHelper
end

app/views/admin/assignments/_form.html.erb
<%= form_for [:admin, @assignment], html: { class: 'form-horizontal', 'data-parsley-validate': '' } do |f| %>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.label 'Title' %>
      <%= f.text_field :title, required: true, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.label 'Description' %>
      <%= f.text_area :description, required: true, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.label 'Submit Date' %>
      <%= f.datetime_field :due_date, required: true, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-12">
      <%= f.submit class: 'btn btn-primary float-left' %>
      <%= link_to 'Cancel', admin_assignments_path, class: 'btn btn-success float-right' %>
    </div>
<% end %>

app/views/admin/assignments/edit.html.erb
<div class="container">
  <h4>Edit Assignment</h4>
  <%= render 'form' %>
</div>

app/views/admin/assignments/index.html.erb
<div class="container">
  <%= render 'shared/header' %>
  </br>
  </br>
  <div class="row">
    <div class="col-lg-12">
      <h2 class= 'float-left'>All Assignments!</h2>
      <%= link_to "Create Assignment", new_admin_assignment_path, class: "btn btn-info float-right" %>
    </div>
  </div>
  </br>
  <div class="row">
    <% if @assignments.present? %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th class='text-center'>Title</th>
            <th class='text-center'>Description</th>
            <th class='text-center'>Due Date</th>
            <th class='text-center'>Upload Assignment</th>
            <th class='text-center'>Actions</th>    
          </tr>
        </thead>
        <% @assignments.each do |assignment| %>
          <tbody>
            <tr>
              <td class='text-center'><%= assignment.title %></td>
              <td class='text-center'><%= assignment.description.truncate(20) %></td>
              <td class='text-center'><%= assignment.due_date.strftime('%a %d %b %Y by %l:%M %p') %></td>
              <td class='text-center'>
                <% if assignment.sent_to_users == true %>
                  <%= link_to 'Uploaded', 'javascript:void(0)', class: 'btn btn-secondary' %>
                <% else %>
                  <%= link_to 'Upload', sent_to_users_admin_assignment_path(assignment), method: :post, class: 'btn btn-secondary' %>
                <% end %>
              </td>
              <td class='text-center'><%= link_to 'Edit', edit_admin_assignment_path(assignment), class: 'btn btn-warning' %>
              <%= link_to 'Show', admin_assignment_path(assignment), class: 'btn btn-primary' %>
              <%= link_to 'Delete', admin_assignment_path(assignment), method: :delete, class: 'btn btn-danger' %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    <% else %>
      <h4 class='text-center'>You have not created any assignments yet.</h4>
    <% end %>
  </div>
</div>

app/views/admin/assignments/new.html.erb
<div class="container">
	<h4>Create a new Assignment</h4>
  <%= render 'form' %>
</div>

app/views/admin/assignments/show.html.erb
<div class="container">
  <%= render 'shared/header' %>
  </br>
  </br>
  <div class="row">
    <div class="col-lg-12">
      <h2 class= 'float-left'>Assignment Details</h2>
      <%= link_to "Back", admin_assignments_path, class: "btn btn-info float-right" %>
    </div>
  </div>
  </br>
  <div class="row">
    <% if @assignment.present? %>
      <table class="table table-bordered table-striped table-hover">
        <tr>
          <th class='text-center'>Title</th>
          <td class='text-center'><%= @assignment.title %></td>
        </tr>
        <tr>
          <th class='text-center'>Description</th>
          <td class='text-center'><%= @assignment.description %></td>
        </tr>
        <tr>
          <th class='text-center'>Due Date</th>
          <td class='text-center'><%= @assignment.due_date.strftime('%a %d %b %Y by %l:%M %p') %></td>
        </tr>
      </table>
    <% else %>
      <h4 class='text-center'>No details</h4>
    <% end %>
  </div>
  </br>
  </br>
  <div class="row">
    <div class="col-lg-12">
      <h2 class= 'float-left'>All Uploaded Assignments of users</h2>
    </div>
  </div>
  </br>
  <div class="row">
    <% if @assignment_users.present? %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th class='text-center'>Name</th>
            <th class='text-center'>Email</th>
            <th class='text-center'>Assignment File</th>
            <th class='text-center'>Sumitted Date</th>
          </tr>
        </thead>
        <% @assignment_users.each do |assignment_user| %>
          <tbody>
            <tr>
              <td class='text-center'><%= assignment_user.user.name.humanize %></td>
              <td class='text-center'><%= assignment_user.user.email %></td>
              <td class='text-center'>
                <% if assignment_user.file&.attached? %>
                  <%= link_to assignment_user.file.blob.filename, rails_blob_path(assignment_user.file, disposition: "attachment") %>
                <% else %>
                  Not Uploaded yet
                <% end %>
              </td>
              <td class='text-center'><%= assignment_user.submit_date.localtime.strftime('%a %d %b %Y at %l:%M %p') %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    <% else %>
      <h4 class='text-center'>None of the users have uploaded any assignment yet.</h4>
    <% end %>
  </div>
</div>